Himalayan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.api.urls")),
    path('shop/', include("shopapp.urls")),
    path('api/', include("trek.api.urls")),
    path('cab/', include("cab.urls")),
    
#
 ]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cab/urls.py
from django.urls import path
from . import views

app_name = 'cab'

urlpatterns =[
   path('',views.cab_home_page,name='home'),
]

shopapp/urls.py
from django.urls import path
from .import views

app_name = 'shopapp'

urlpatterns = [
   path('',views.shop_home_page,name='home_page'),#home page/
   path('shop/',views.product_page,name='product'), #/product/shop navbar
   # path('product/<int:id>/',views.single_product_page,name='single_page'), #/shop/product/1/2/3/4
   path('about/',views.about_page, name='about'),
   path('contact/',views.contact_page, name='contact'),
   path('blog/',views.blog_page, name='blog'),
   path('cart/',views.cart_page, name='cart'),
]

shopapp/models.py
from django.db import models
from core.models import CustomUser

# Create your models here.

class Category(models.Model):
   name=models.CharField(max_length=100)
   description=models.TextField(blank=True)

def __str__(self):
   return self.name

class product(models.Model):
   category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name='products')
   name = models.CharField(max_length=100)
   price = models.DecimalField(max_digits="15",decimal_places="2")
   description = models.TextField()
   stock = models.PositiveIntegerField()
   image =models.ImageField(upload_to='products/')

def __str__(self):
   return self.name

class wholesaleorder(models.Model):
   STATUS_CHOICES=[
      ('pending','Pending'),
      ('confirmed','Confirmed'),
      ('shipped','Shipped'),
      ('delivered','Delivered'),
   ]
   user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
   product=models.ForeignKey(product,on_delete=models.CASCADE)
   quantity=models.IntegerField()
   total_prices=models.DecimalField(max_digits=10,decimal_places=2)
   order_date=models.DateTimeField(auto_now_add=True)
   status=models.CharField(max_length=20,choices=STATUS_CHOICES,default='pending')

def __str__(self):
   return f"{self.product.name} - {self.user.username}"

shopapp/views.py
from django.shortcuts import render
from shopapp.models import product


# Create your views here.

def shop_home_page(request):
   return render(request, 'shop/home.html')

def product_page(request):
   products=product.objects.all() #fetch all the products form the DB
   return render(request, 'shop/product.html',{'products':products})

def single_product_page(request, id):
    try:
        single_product = product.objects.get(id=id)
    except product.DoesNotExist:
        return render(request, 'shop/404.html')  # Optional error page
    return render(request, 'shop/single_product.html', {'product': single_product})

#blog 
def blog_page(request):
   return render(request, 'shop/blog.html')

#about
def about_page(request):
   return render(request, 'shop/about.html')

#contact
def contact_page(request):
   return render(request, 'shop/contact.html')

def cart_page(request):
   return render(request, 'shop/cart.html')

shopapp/templates/shop/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Document</title>
</head>
<body>
   <h1>Coming Soon</h1>
</body>
</html>

shopapp/templates/shop/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Document</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" type="text/css" href="{% static 'css/inde.css' %}">

</head>
<body>
   <section id="header">
      <a href="#"><img src="{% static 'images/logo.png' %}" class="logo" alt=""></a>

      <div>
         <ul id="navbar">
            <li><a class="active" href="index.html">Home</a></li>
            <li><a href="{% url 'shopapp:product' %}">Shop</a></li>
            <li><a href="{% url 'shopapp:blog' %}">Blog</a></li>
            <li><a href="{% url 'shopapp:about' %}">About</a></li>
            <li><a href="{% url 'shopapp:contact' %}">Contact</a></li>
            <li><a href="{% url 'shopapp:cart' %}">
               <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            </a></li>

         </ul>
      </div>
   </section>


   <section id="hero">


      <!-- <img src="{% static 'images/cheese.jpg' %}" alt="test"> -->

         <h4>Crafted By Nature</h4>
         <h2>Perfected by Himalayas</h2>
         <h1>Mountainous Bites of Purity</h1>
         <p>“Yak Products From the Himalayas”</p>
         <button>Shop Now</button>
   </section>

   <section id="feature" class="section-p1">
      <div class="fe-box">
         <img src="{%static 'images/feature/free.png' %}" width="200" height="200" alt="">
         <h6>Free Shipping</h6>
         </div>
         <div class="fe-box">
         <img src="{%static 'images/feature/online.png' %}" width="200" height="200" alt="">
         <h6>Online Order</h6>
      </div>
      <div class="fe-box">
         <img src="{% static 'images/feature/authentic.png' %}" width="200" height="200" alt="">
         <h6>Authentic Product</h6>
      </div>
      <div class="fe-box">
         <img src="{% static 'images/feature/customer.png' %}" width="200" height="200" alt="">
         <h6>24/7 Customer Care</h6>
      </div>
   </section>
</body>
</html>